config/routes.rb
Trackr::Application.routes.draw do
  

  resources :companies do
    put :activity, :on => :member
    put :updatestatus, :on => :member
    resources :contacts, :on => :member do
      get :show_modal, :on => :member
    end
    resources :logs, only: [:create, :destroy, :update, :edit]
    get :autocomplete_user_name, :on => :collection
  end
  resources :users do
    put :editlevel, :on => :member
    resources :companies, :on=> :member, only: [:index]
  end
  
  resources :teams do
    get :autocomplete_user_name, :on => :collection
    put :activity, :on => :member
    resources :companies, :on=> :member, only: [:index]
  end

  resources :contacts do
    put :activity, :on => :member
  end

  resources :logs, only: [:create, :destroy, :update, :edit]

  
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'static#home'

  match '/about',     to: 'static#about'
  match '/contactus', to: 'static#contact'
  match '/signup',    to: 'users#new'
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy', via: :delete

  match "/500", to:'static#500'
  match "/422", to:'static#422'
  match "/404", to:'static#404'
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  level      :integer
#  phone      :string(255)
#  identifier :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :identifier, :name, :phone, :password, :password_confirmation
  has_secure_password

  before_save {|user| user.email = email.downcase}
  before_save :create_remember_token
  before_create :set_deactivated
  has_and_belongs_to_many :teams

  has_many :contacted_companies,
  :class_name => 'Company',
  :foreign_key => 'poc_id'

  has_many :managed_companies,
  :class_name => 'Company',
  :foreign_key => 'manager_id'
  
  has_many :logs
  validates :name, presence: true , uniqueness: true,length: {minimum:2,maximum:100}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },uniqueness: true;
  VALID_PHONE_REGEX = /\A\+?[0-9\-\s\(\)]*\z/
  validates :phone, format: {with: VALID_PHONE_REGEX}
  validates :identifier,uniqueness:true
  validates :password, presence:true , length: {minimum:6 }, :on => :create
  validates :password_confirmation, presence: true, :on => :create

   def role 
    if self.level == Global.level[:superadmin]
      return "superadmin"
    elsif self.level==Global.level[:admin]
      return "admin"
    elsif self.level <= Global.level[:poweruser]
      return "poweruser"
    elsif self.level <= Global.level[:user]
      return "user"
    elsif self.level == Global.level[:disabled]
      return "disabled"
    elsif self.level == Global.level[:deleted]
      return "deleted"
    end
  end

  def superadmin?
    if self.level==Global.level[:superadmin]
      true
    end
  end

  def admin?
    if self.level <= Global.level[:admin]
      return true
    end
  end

  def poweruser?
    if self.level <= Global.level[:poweruser]
      return true
    end
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

    def correct_user
      @user=User.find(params[:id])

      redirect_to root_path, error:"Access Denied" unless current_user?(@user)
    end

    def set_deactivated
      self.level=127
    end

   

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index,:show,:edit,:update,:destroy]
  before_filter :correct_user, only: [:edit,:update]
  before_filter :admin_user, only: [:destroy,:editlevel]
  def index

    @counterstart=1;
    if current_user.superadmin?
      @users=User.all
    else
      @users=User.where(level: Global.level[:superadmin] .. Global.level[:disabled])
    end
    @pagenum= params[:page]? params[:page].to_i : 1
    @counterstart=(User.per_page*(@pagenum-1))+1
    respond_to do |format|
      format.html
      format.json do 
        @allusers = User.where(level: Global.level[:superadmin] .. Global.level[:disabled]).where("name like ?", "%#{params[:q]}%") 
        render :json => @allusers 
        
      end
      @usr=User.all
      format.csv { render text: User.to_csv() }
      #format.xlsx { send_data @usr.to_csv(col_sep: "\t") }
      format.xlsx
    end
    
  end
  def show
  	@user=User.find(params[:id])
  end

  def new
  	@user= User.new
  end

  def create
  	@user = User.new (params[:user])
  	if @user.save
      @team=Team.new
      @team.name=@user.name
      @team.user_tokens="#{@user.id}"
      @team.set_single
      @team.save
      sign_in @user
  		flash[:success] = "Welcome to the Sample App!"
      
  		redirect_to @user
      
  	else
  		render 'new'
  	end
  end

  def editlevel
    @user=User.find(params[:id])
    level=params[:level]
    if level
      @user.level = level
    else
      @user.level = 127
    end
    @user.save
    redirect_to users_path
  end
  def User.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end
  end
  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update_attributes(params[:user])
        flash[:success]="Profile updated"
        sign_in @user
        redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success]="User Removed"
    redirect_to users_url
  end

  private
    def correct_user
      @user=User.find(params[:id])

      redirect_to root_path, error:"Access Denied" unless current_user?(@user)
    end

end

app/helpers/users_helper.rb
module UsersHelper

	
end

app/views/users/_form.html.erb
<div>
<%= form_for @user, :html => {:class => "form-horizontal span12"} do |f| %>
  <fieldset>
  <%=render 'shared/error_messages', object: f.object %>
    <% if @user.id %>
      <legend>Edit <%= @user.name %>  details</legend>
    <% else %>
      <legend>Add new user</legend>
    <% end %>
    <div class="control-group">
      <%= f.label :name , :class =>"control-label"%>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>

    <div class="control-group">
      <%=f.label :email, :class => "control-label" %>
      <div class="controls">
        <%=f.text_field :email %>
      </div>
    </div>

    <div class="control-group">
      <%=f.label :phone , :class => "control-label"%>
      <div class="controls">
        <%=f.text_field :phone %>
      </div>
    </div>

    <div class="control-group">
      <%=f.label :identifier, :class => "control-label" %>
      <div class="controls">
        <%=f.text_field :identifier %>
      </div>
    </div>

    <div class="control-group">
      <%=f.label :password, :class => "control-label" %>
      <div class="controls">
        <%=f.password_field :password %>
      </div>
    </div>

    <div class="control-group">
      <%=f.label :password_confirmation, :class => "control-label" %>
      <div class="controls">
        <%=f.password_field :password_confirmation %>
      </div>
    </div>
    <hr />
    <div class="controls">
      <%= f.submit "Update",class:"btn btn-primary" %>
      <%= link_to "Back", goback, class:"btn btn-inverse" %>
    </div>
  </fieldset>
<% end %>
</div>

app/views/users/_user_edit_button.html.erb
<!--
This file has user level numbers, 
 -->
<% if right %>
  <div class="btn-group pull-right">
<% else %>
  <div class="btn-group">
<% end %>
  <%= link_to "User", user, :class => "btn btn-primary" %>
  <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" >
   <li><%= link_to "Managed Companies" , user_companies_path(user) %></li>
  	<% if user.level >= Global.level[:disabled] %>
    <li><%= link_to "Approve",editlevel_user_path(user,level: Global.level[:user] ),method: :put %></li>
    <% end %>
    <% if !current_user?(user) && !user.admin? %>
    <li><%= link_to "Disable User",editlevel_user_path(user,level: Global.level[:disabled]),method: :put %></li> 
    <% end %>
    <% if ((current_user.admin? && !user.superadmin?) || (current_user.superadmin?)) && !current_user?(user) %>
      <li><%= link_to "Delete User", editlevel_user_path(user,level: Global.level[:deleted]),method: :put  %></li>
    <% end %>
  	<% if current_user.superadmin? && !current_user?(user) %>
      <li><%= link_to "Make admin",editlevel_user_path(user,level: Global.level[:admin]),method: :put %></li>
    <% end %>
    <% if !user.admin? %>
    <li><%= link_to "Make poweruser",editlevel_user_path(user,level:Global.level[:poweruser]),method: :put %> </li>
    <% end %>
    <% if current_user.superadmin? && !current_user?(user) %>
      <li class="divider"></li>
      <li><%= link_to "Permanently Delete User",user,method: :delete, data: {confirm: "This will permanently delete the user, the action CANNOT be undone, are you sure ?"} %></li>
    <% end %>
  </ul>
</div>

app/views/users/edit.html.erb
<% provide(:title,"Edit #{@user.name}") %>

<h1>Update your profile</h1>

<div class="row">
	<div class="span12">
		 <%= render 'users/form', object: @user %>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title,"Users") %>

<h1>User List</h1>
<p class="pull-right">
  Download:
  <%= link_to "CSV", users_path(format: "csv") %> |
  <%= link_to "Excel", users_path(format: "xlsx") %>
</p>
<table class="table table-striped table-hover table-bordered" id="user-table">
  <thead>
    <tr>
      <th>Sl No.</th>
      <th class="hidden-desktop hidden-tablet visible-phone">Details</th>
      <th class="hidden-phone">Name</th>
      <th class="hidden-phone">Email</th>
      <th class="hidden-phone">Phone</th>
      <th class="hidden-phone">Identifier</th>
      <th class="hidden-phone">Level</th>
      <th>More</th>
    </tr>
  </thead>
  <tbody>
    <% counter = @counterstart %>
    <% @users.each do |user| %>
    <tr>
      <td><%= counter %></td>
      <td class="hidden-desktop hidden-tablet visible-phone"><%=link_to user.name, user%><br/> <%= user.email %><br/> <%= user.phone %></td>
      <td class="hidden-phone"><%=link_to user.name, user%></td>
      <td class="hidden-phone"><%= user.email %></td>
      <td class="hidden-phone"><%= user.phone %></td>
      <td class="hidden-phone"><%= user.identifier %></td>
      <td class="hidden-phone"><%= user.role %></td>
      <% if current_user.admin? %>
      <% right = true %>
      <td><%= render 'users/user_edit_button',{ user: user , right: right}%></td>
      <% else %>
      <td><%= link_to "User", user, class:"btn btn-primary" %></td>
      <% end %>
      <% counter+=1 %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.xlsx.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">Level</Data></Cell>
        <Cell><Data ss:Type="String">Phone</Data></Cell>
        

      </Row>
      <% @users=User.all %>
    <% @users.each do |user| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= user.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%=  user.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%=  user.level %></Data></Cell>
        <Cell><Data ss:Type="String"><%=  user.phone %></Data></Cell>
        
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/users/new.html.erb
<% provide(:title,'Sign Up') %>
<div class="row-fluid">
  <div class="span12">
    <%= render 'users/form', object: @user %>
  </div>
</div> <!-- /container -->

app/views/users/show.html.erb
<% provide(:title,@user.name) %>

<h1><%=@user.name %>  <small><%= @user.identifier %></small>
	<% if current_user.admin? %>
	<%= render 'users/user_edit_button', { user: @user , right: false} %>
	<% end %>
    </h1>
<em>is <%=@user.role %></em>
<hr />
<address>
	<strong><%=@user.email %></strong><br/>
	<%= @user.phone %><br />
</address>