config/routes.rb
Trackr::Application.routes.draw do
  

  resources :companies do
    put :activity, :on => :member
    put :updatestatus, :on => :member
    resources :contacts, :on => :member do
      get :show_modal, :on => :member
    end
    resources :logs, only: [:create, :destroy, :update, :edit]
    get :autocomplete_user_name, :on => :collection
  end
  resources :users do
    put :editlevel, :on => :member
    resources :companies, :on=> :member, only: [:index]
  end
  
  resources :teams do
    get :autocomplete_user_name, :on => :collection
    put :activity, :on => :member
    resources :companies, :on=> :member, only: [:index]
  end

  resources :contacts do
    put :activity, :on => :member
  end

  resources :logs, only: [:create, :destroy, :update, :edit]

  
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'static#home'

  match '/about',     to: 'static#about'
  match '/contactus', to: 'static#contact'
  match '/signup',    to: 'users#new'
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy', via: :delete

  match "/500", to:'static#500'
  match "/422", to:'static#422'
  match "/404", to:'static#404'
  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :address, :designation, :email, :landline, :mobile, :name, :active
  belongs_to :company
  has_many :logs

  validates :name, presence: true , length: {minimum:2,maximum:100}
  validates :address, length: {minimum:0,maximum:1000}
  VALID_PHONE_REGEX = /\A[[\+?[0-9\-\s\(\)\/\,]*]\,]*\z/
  validates :mobile, format: {with: VALID_PHONE_REGEX}
  validates :landline, format: {with:VALID_PHONE_REGEX}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }
  before_save {|contact| contact.email = email.downcase}
  before_create {|contact| contact.active = true}

  

  def default?
    self.default
  end

  def deleted?
    !self.active
  end

  def active?
    self.active
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  before_filter :admin_user, only: [:destroy]
  before_filter :power_user
  
  def activity
    @contact=Contact.find(params[:id])
    if @contact.company
      can_view_else_redirect(@contact.company)
    elsif !(current_user.admin?)
      flash[:error]="Access Denied"
      redirect_to goback
    end
    @contact.active=params[:active]
    @contact.save
    redirect_to goback
  end

  def index
    if params[:company_id].nil?
      if current_user.superadmin?
        @contacts = Contact.includes(:company).all
      elsif current_user.admin?
        @contacts = Contact.includes(:company).where(:active => true)
      else
        flash[:error]="Access Denied"
        redirect_to goback
      end
    else

      @company = Company.find(params[:company_id])
      can_view_else_redirect(@company)
      if current_user.superadmin?
        @contacts = @company.contacts
      else
        @contacts = @company.contacts.where(:active => true)
      end
    end
    respond_to do |format|
      format.html # /
      format.json { render json: @contacts}
      format.xlsx 
      format.csv { render text: Contact.to_csv() }
    end
  end

  def new
    if params[:company_id] == nil
      flash[:error] = "Cannot create contact without company"
      redirect_to root_path
    else

      @company = Company.find(params[:company_id])
      can_view_else_redirect(@company)
      @contact = @company.contacts.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @contact }
      end
    end
  end

  def show_modal
    @company = Company.find(params[:company_id])
    can_view_else_redirect(@company)
    @contact = Contact.find(params[:id])
  end
  def show
    @contact = Contact.find(params[:id])
    if @contact.company_id
      @company = Company.find(@contact.company_id)
      can_view_else_redirect(@company)
    else
      unless current_user.admin?
        flash[:error] ="Access Denied"
        redirect_to goback 
      end
    end
    unless @contact
      flash[:error] = "Contact has left the building"
      if @company
        redirect_to @company
      else
        redirect_to contacts
      end
    end
    respond_to do |format|
      format.html 
      format.json {render json: @contact}
    end 
  end
  def edit
    @contact = Contact.find(params[:id])
    @company = Company.find(@contact.company_id)
    if (@company)
      can_view_else_redirect(@company)
    else
      unless current_user.admin?
        flash[:error] ="Access Denied"
        redirect_to goback 
      end
    end
  end

  # POST /contacts
  # POST /contacts.json
  def create
    if params[:company_id].nil?
      flash[:error] = "Cannot create contact without company"
      redirect_to root_path
    end
    @company = Company.find(params[:company_id])
    @contact = @company.contacts.build(params[:contact])
    can_view_else_redirect(@company)
    if @contact.save
      flash[:success] = "Contact added!"
      redirect_to @company
    else
      render 'new'
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])
    @company = Company.find(@contact.company_id)
    can_view_else_redirect(@company)
    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        #if reset_default then

        flash[:success] = "Contact was edited"
        format.html { redirect_to @company}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end
  def Contact.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |user|
        csv << contact.attributes.values_at(*column_names)
      end
    end
  end
  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @company = @contact.company
    if @company.default_contact_id == @contact.id
      @company.default_contact_id = nil
      @company.save
    end
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
  private
    def correct_user
      redirect_to root_path, error:"Access Denied" unless current_user.poweruser?
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact_button.html.erb
<!--
This file has user level numbers, 
 -->
<% if right %>
  <div class="btn-group pull-right">
<% else %>
  <div class="btn-group">
<% end %>
  <%= link_to "Contact", contact, :class => "btn btn-primary" %>
  <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" >
    <li> <%= link_to "Edit user", edit_contact_path(contact) %></li>
    <% if contact.deleted? %>
      
      <li> <%= link_to "Undelete user", activity_contact_path(contact,active: true), method: :put %></li>
    <% else %>  
      <li> <%= link_to "Delete user", activity_contact_path(contact,active: false), method: :put %></li>
    <% end %>
    <% if current_user.superadmin?  %>
      <li><%= link_to "Permanently Delete User",contact,method: :delete, data: {confirm: "This will permanently delete the user, the action CANNOT be undone, are you sure ?"} %></li>
    <% end %>
  </ul>
</div>

app/views/contacts/_form.html.erb
<%= form_for [@company,@contact], :html => {:class => "form-horizontal span12"} do |f| %>

  <fieldset>
    <% if @contact.id %>
      <legend>Edit <%= @company.name %> contact details</legend>
    <% else %>
      <legend>Add new contact for <%= @company.name %></legend>
    <% end %>
    <%=render 'shared/error_messages', object: f.object %>
    <div class="control-group">
      <%= f.label :name , :class =>"control-label"%>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :company , :class =>"control-label"%>
      <div class="controls">
        <span class="input-large uneditable-input"><%= @company.name %></span>
        
      </div>
    </div>
    <div class="control-group">
      <%= f.label :designation , :class =>"control-label"%>
      <div class="controls">
        <%= f.text_field :designation %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :mobile , :class =>"control-label" %>
      <div class="controls">
        <%= f.text_field :mobile %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :landline , :class =>"control-label"%>
      <div class="controls">
        <%= f.text_field :landline %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :email , :class =>"control-label"%>
      <div class="controls">
        <%= f.text_field :email %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :address , :class =>"control-label"%>
      <div class="controls">
        <%= f.text_area :address , :rows => "3"%>
      </div>
    </div>
    <div class="controls">
      <% if @contact.id %>
        <%= f.submit "Update", class: "btn btn-primary" %>
      <% else %>
        <%= f.submit "Add Contact", class: "btn btn-primary" %>
      <% end %>
      <%= link_to "Back", @company,class: "btn btn-inverse" %>
    </div>
  </fieldset>
<% end %>

app/views/contacts/_modal.html.erb
<div class="modal-header">
    <a href="#" data-dismiss="modal" aria-hidden="true" class="close">×</a>
    <h3><%= @contact.name %> <small><%= @contact.designation %></h3>
  </div>
  <div class="modal-body center">
      <p>
      Mobile : <a href="tel:<%= @contact.mobile %>"><%=@contact.mobile %></a><br/ >
      Landline : <a href="tel:<%= @contact.landline %>"><%=@contact.landline %> </a> <br/>
      Email : <a href='mailto:<%=@contact.email%>'><%= @contact.email %></a>
      <br/>
      Address :
      <br/>
      <address>
        <%= simple_format(@contact.address) %>
      </address></p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <%= link_to "Edit" , edit_company_contact_path(@company, @contact), class: "btn btn-primary", data: {company_id: @contact.company.id} %>
    <%= link_to "Delete", activity_contact_path(@contact,active: false), class:"btn btn-danger" , method: :put %>
  </div>

app/views/contacts/edit.html.erb
<% provide(:title,@contact.name) %>
<div class="row-fluid">
  <span class="span12">
    <%= render 'contacts/form' , object: {@company => @company, @contact => @contact} %>
  </span>
</div>

app/views/contacts/index.html.erb
<% provide(:title,"Contacts") %>
<div class="row-fluid">
<span class="span12">
<h1>Contact List
<% if @company %>
<%= link_to "Add Contact to #{@company.name} ", new_company_contact_path(:company_id => @company.id),:class => "pull-right btn btn-primary" %>
<% end %>
</h1> 

<table class="table table-striped table-hover table-bordered" id="contact-table">
  <thead>
    <tr>
      <th class="hidden-desktop hidden-tablet">Details</th>
      <th class="hidden-phone">Name (Designation)</th>
      <th class="hidden-phone">Phone </th>
      <th class="hidden-phone">Email</th>
      <th class="hidden-phone">Company</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
    <tr>
      <td class="hidden-desktop hidden-tablet">
          <%= contact.name %> ( <%= contact.designation %> )
          <% if contact.company %><%= " @ #{contact.company.name}" %><% end %> <br/>
          (O)<%= contact.landline %> (M) <%= contact.mobile %><br />
          <%= contact.email %></td>
      <td class="hidden-phone" ><%= contact.name %> ( <%= contact.designation %> )</td>
      <td class="hidden-phone" >(O)<%= contact.landline %>, (M) <%= contact.mobile %></td>
      <td class="hidden-phone" ><%= contact.email %></td>
      <td class="hidden-phone" ><% if contact.company %><%= contact.company.name %><% end %></td>
      <td><%= render 'contacts/contact_button', {contact: contact, right: true }%></td>
    </tr>
  
<% end %>
</tbody>
</table>

app/views/contacts/index.xlsx.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Designation</Data></Cell>
        <Cell><Data ss:Type="String">Address</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">Mobile Number</Data></Cell>
        <Cell><Data ss:Type="String">Landline</Data></Cell>
        <Cell><Data ss:Type="String">Default Contact</Data></Cell>
        <Cell><Data ss:Type="String">Active</Data></Cell>
        

      </Row>
      <% @contacts=Contact.all %>
    <% @contacts.each do |contact| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= contact.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%=  contact.desination %></Data></Cell>
        <Cell><Data ss:Type="String"><%= contact.address %></Data></Cell>
        <Cell><Data ss:Type="String"><%=  contact.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%=  contact.mobile %></Data></Cell>
        <Cell><Data ss:Type="String"><%=  contact.landline %></Data></Cell>
        <Cell><Data ss:Type="String"><%=  contact.default %></Data></Cell>     
        <Cell><Data ss:Type="String"><%=  contact.active %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/contacts/new.html.erb
<div class="row-fluid">
    <span class="span12">
        <%= render 'contacts/form', object: {@company => @company, @contact => @contact} %>
</span>
</div>

app/views/contacts/show.html.erb
<% provide(:title,@contact.name) %>
<div class="row-fluid">
<span class="span12">
<h1><%=@contact.name %>  <small><%= @contact.designation %></small></h1>
<hr />
<%= render 'contacts/contact_button',{ contact: @contact , right: false } %>
<hr/>
<p>
	Contact of <%= link_to @contact.company.name , @contact.company %>
</p>

<address>
  Mail : <strong><%=@contact.email %></strong><br/>
  Mobile : <%= @contact.mobile %><br />
  Landline: <%= @contact.landline %><br />
  Address : <br/> <%= simple_format(@contact.address) %>
</address>
</span>
</div>

app/views/contacts/show_modal.js.erb
$(document).ready(function() {
 
$('#contact-modal').html('<%= escape_javascript(render "contacts/modal", :object => @contact) %>');
});