config/routes.rb
Trackr::Application.routes.draw do
  

  resources :companies do
    put :activity, :on => :member
    put :updatestatus, :on => :member
    resources :contacts, :on => :member do
      get :show_modal, :on => :member
    end
    resources :logs, only: [:create, :destroy, :update, :edit]
    get :autocomplete_user_name, :on => :collection
  end
  resources :users do
    put :editlevel, :on => :member
    resources :companies, :on=> :member, only: [:index]
  end
  
  resources :teams do
    get :autocomplete_user_name, :on => :collection
    put :activity, :on => :member
    resources :companies, :on=> :member, only: [:index]
  end

  resources :contacts do
    put :activity, :on => :member
  end

  resources :logs, only: [:create, :destroy, :update, :edit]

  
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'static#home'

  match '/about',     to: 'static#about'
  match '/contactus', to: 'static#contact'
  match '/signup',    to: 'users#new'
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy', via: :delete

  match "/500", to:'static#500'
  match "/422", to:'static#422'
  match "/404", to:'static#404'
  

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :address, :location, :name, :phone, :url, 
                  :poc_name,:manager_name,:team_tokens, :description, :status,
                  :status_text, :default_contact, :default_contact_id, :poc_id,:manager_id
  
  attr_reader :team_tokens

  belongs_to :pointofcontact, 
  :class_name => 'User', 
  :foreign_key => 'poc_id'

  belongs_to :manager,
  :class_name => 'User',
  :foreign_key => 'manager_id'
  
  has_many :contacts

  has_many :logs
  def poc_name
    pointofcontact.try(:name)
  end

  belongs_to :default_contact,
  :class_name => 'Contact',
  :foreign_key => 'default_contact_id'

  def poc_name=(name)
    self.pointofcontact = User.find_by_name(name) if name.present?
  end

  def manager_name
    manager.try(:name)
  end

  def manager_name=(name)
    self.manager = User.find_by_name(name) if name.present?
  end

  has_and_belongs_to_many :teams
  
  def team_tokens=(ids)
    self.team_ids=ids.split(',')
  end

  before_create :set_status
  before_create :set_active
  
  def status_text
    code=self.status
    keys=Global.status

    if code.nil?
      return "Status undefined"
    elsif code <= keys[:nocontact]
      "No contact exists"
    elsif code <= keys[:uncontacted]
      "Yet to contact"
    elsif code <= keys[:invitesent]
      "Invitation Sent"
    elsif code <= keys[:inviteaccepted]
      "Invitation Accepted"
    elsif code <= keys[:jafsent]
      "JAF Sent"
    elsif code <= keys[:jaffilled]
      "JAF Filled"
    elsif code <= keys[:pptset]
      "PPT Scheduled"
    elsif code <= keys[:pptdone]
      "PPT Done"
    elsif code <= keys[:testset]
      "Test Scheduled"
    elsif code <= keys[:testdone]
      "Test Completed"
    elsif code <= keys[:rejected]
      "Rejected Invitation"
    elsif code <= keys[:novacancy]
      "No Vacancy"
    elsif code <= keys[:contactlater]
      "Contact Later"
    elsif code <= keys[:blacklisted]
      "Blacklisted"
    end
  end

  def set_status
    self.status = Global.level[:nocontact]
  end

  def set_inactive
    self.active=false
  end

  def set_active
    self.active=true
  end

  validates :name, presence: true ,uniqueness: true, length: {minimum:2,maximum:100}
  validates :address, length: {minimum:0,maximum:1024}
  validates :location,length: {minimum:0,maximum:100}
  VALID_PHONE_REGEX = /\A\+?[0-9\-\s\(\)\/{ext:}]*\z/
  #validates :phone, format: {with: VALID_PHONE_REGEX, message: "Phone can be Numerals, (, ), / (For multiple numbers), Space , - , ext: (For extension). + symbol allowed at beggining"}
  VALID_URL_REGEX = /\A[[a-z\d\-.\/:]+\.[a-z]+]?\z/i
  #validates :url, format: {with: VALID_URL_REGEX}
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_filter :signed_in_user
  before_filter :power_user

    #before_filter :correct_user, only: []
  before_filter :admin_user, only: [:destroy]
  
  autocomplete :user, :name, :full => true 
  def new
  	@company=Company.new
  end
  def create
  	@company = Company.new (params[:company])
    @company.teams << current_user.teams.first
  	if @company.save
      #sign_in @user
  		flash[:success] = "Company created"
      
  		  redirect_to @company
      
  	else
  		render 'new'
  	end
  end
  def show
    @company=Company.find(params[:id])
    can_view_else_redirect (@company)
    @contacts=@company.contacts
    @default=@company.default_contact
    @logs=@company.logs.order("created_at DESC").paginate(page: params[:page])
    @newlog=@company.logs.build
  end
  def edit
    @company=Company.find(params[:id])
    @contacts=@company.contacts.where(:active => true)
    can_view_else_redirect (@company)
  end
  def destroy
    Company.find(params[:id]).destroy
    flash[:success]="Company Profile Deleted."
    redirect_to companies_url
  end
  def index
    @counterstart=1;
    if params[:team_id]
      @source=Team.find(params[:team_id]).companies.all(:include => [:default_contact,:logs,:teams,:pointofcontact])
    elsif params[:user_id]
      @company_ids=[]
      @source=[]
      @user=User.find(params[:user_id])
      @user.teams.each do |team|
        team.companies.each do |company|
          @company_ids << company.id
        end
      end
      @user.contacted_companies.each do |company|
        @company_ids << company.id
      end
      #@company_ids.uniq!
      @source = Company.find_all_by_id(@company_ids,:include => [:default_contact,:logs,:teams,:pointofcontact])
    else
      @source=Company.all(:include => [:default_contact,:logs,:teams,:pointofcontact])
    end
    if current_user.superadmin?
      @companies=@source
    elsif current_user.admin?
      @companies=@source.select{|c| c.active?}
    elsif current_user.poweruser?
      @companies=[]
      @allcompanies=@source.select{|c| c.active?}
      @allcompanies.each do |company|
        if ((company.teams & current_user.teams).any?) || (company.poc_id == current_user.id)
            @companies << company
        end
      end
      
    end
    respond_to do |format|
        format.html # /
        format.json { render json: @companies}
        format.csv { render text: Company.to_csv(@companies) }
        format.xlsx
    end
  end
  def update
    @company=Company.find(params[:id])
    can_view_else_redirect (@company)
    if @company.update_attributes(params[:company])
        flash[:success]="Profile updated"
        #sign_in @user
        redirect_to @company
    else
      render 'edit'
    end
  end
  def updatestatus
    @company=Company.find(params[:id])
    can_view_else_redirect (@company)
    @log = @company.logs.build(params[:log])
    @prev_status=@company.status_text
    @company.status=params[:status]
    @log.content = "Status changed from #{@prev_status} to #{@company.status_text}"
    @log.user_id=current_user.id
    begin
      @log.save
    rescue Exception => e

    end
    @company.status=params[:status]
    @company.save
    redirect_to @company
  end
  def activity
    @company=Company.find(params[:id])
    can_view_else_redirect (@company)
    @company.active=params[:active] if params[:active]
    @company.save
    redirect_to @company
  end
  def Company.to_csv(companies)
    CSV.generate do |csv|
      csv << column_names
      all.each do |company|
        csv << company.attributes.values_at(*column_names)
      end
    end
  end
  private
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end  
    end

    def correct_user
      @user=User.find(params[:id])

      redirect_to root_path, error:"Access Denied" unless current_user?(@user)
    end

     def admin_user
      redirect_to(root_path) unless current_user.admin?
    end


end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_editbutton.html.erb
<% if right %>
  <div class="btn-group pull-right">
<% else %>
  <div class="btn-group">
<% end %>
  <%= link_to "Edit" , edit_company_path(@company), class: "btn btn-primary" %>
  <a class="btn dropdown-toggle " data-toggle="dropdown" href="#">
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" >

    <li><%=   link_to "Undelete" , activity_company_path(@company,active: true), method: :put %></li>
    <li><%=   link_to "Delete" , activity_company_path(@company,active: false), method: :put %></li>
    <% if current_user.superadmin? %>
      <li class="divider"></li>
      <li><%= link_to "Permanently Delete Company",@company,method: :delete, data: {confirm: "This will permanently delete the company, the action CANNOT be undone, are you sure ?"} %></li>
    <% end %>
  </ul>
</div>

app/views/companies/_form.html.erb
<%= form_for @company , html: {class: "form-horizontal span4"} do |f|  %>
  <fieldset>
    <%=render 'shared/error_messages', object: f.object %>
    <legend>
    <%= 
      if @company.id 
        "Editing #{@company.name} details"
      else
        "Adding new company"
      end
    %>
    </legend>
    <div class="control-group">
      <%= f.label :name , class: "control-label" %>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :location , class: "control-label"  %>
      <div class="controls">
        <%= f.text_field :location %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :address, class: "control-label"  %>
      <div class="controls">
        <%= f.text_area :address , rows: 4%>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :url , class: "control-label" %>
      <div class="controls">
        <%= f.text_field :url %>
      </div> 
    </div> 

    <div class="control-group">
      <%= f.label :phone, class: "control-label"  %>
      <div class="controls">
        <%= f.text_field :phone %>
      </div> 
    </div> 

    <div class="control-group">
      <%= f.label :point_of_contact , class: "control-label" %>
      <div class="controls">
        <%= f.autocomplete_field :poc_name, autocomplete_user_name_companies_path %>
      </div>
      Please add yourselves as Point of Contact or else you would NOT be able to access the company once you create it. 
    </div> 

    <div class="control-group">
      <%= f.label :Manager , class: "control-label" %>
      <div class="controls">
        <%= f.autocomplete_field :manager_name, autocomplete_user_name_companies_path %>
      </div>

    </div>
    <% if @company.id %>
      <div class="control-group">
      <%= f.label :default_contact_id ,class: "control-label"%>
      <div class="controls">
        <%= select("company", :default_contact_id, @contacts.collect {|c| [ c.name, c.id ] }, {:include_blank => 'None'}) %>
      </div>
    <% end %>
  </div>
    <hr/>
    <div class="controls">
      <%= f.submit "Update", class: "btn btn-primary" %>
      <%= link_to "Back", goback, class: "btn btn-inverse" %>
    </div>
  </fieldset>
<% end %>

app/views/companies/_newlog.html.erb
<div>
	<h3 class="heading">Contact Log<button class="btn btn-primary btn-success pull-right" id="log-entry-button">New log entry</button></h3>




<%= form_for @newlog, :html => { id: "log-entry-form", class: "form-horizontal"} do |f| %>
<%= render 'shared/error_messages', object: f.object %>
  	<div class="control-group">
  		
    <%= f.text_area :content, placeholder: "Add new conversation" ,rows: 4, class:"span12"%>
    	
    </div>
  <div class="control-group">
  	<%= f.label :contact_id ,class: "control-label"%>
  	<div class="controls">
  		<%= select("log", :contact_id, @contacts.collect {|c| [ c.name, c.id ] }, {:include_blank => 'None'}) %>
  		<%= f.hidden_field :company_id , value: @company.id %>
  		<%= f.hidden_field :user_id , value: current_user.id%>
  	</div>
  </div>
  <div class="controls">
  	<%= f.submit "Add log", class: "btn btn btn-primary" %>
  	<%= link_to "Cancel","#",class: "btn btn-inverse pull-right", id: "log-entry-cancel" %>
  </div>
<% end %>
</div>

app/views/companies/_statuslist.html.erb
<div class="btn-group pull-right">
  <a class="btn dropdown-toggle " data-toggle="dropdown" href="#">
    Status : <%= @company.status_text %>
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu " >
    <li><%= link_to "No contact exists" , updatestatus_company_path(@company,status: Global.status[:nocontact]  ) ,method: :put%></li>
    <li><%= link_to "Yet to contact" , updatestatus_company_path(@company,status: Global.status[:uncontacted]  ) ,method: :put%></li>
    <li><%= link_to "Invitation Sent" ,updatestatus_company_path(@company,status: Global.status[:invitesent]  ) ,method: :put%></li>
    <li><%= link_to "Invitation Accepted" ,updatestatus_company_path(@company,status: Global.status[:inviteaccepted]  ) ,method: :put%></li>
    <li><%= link_to "JAF Sent" ,updatestatus_company_path(@company,status: Global.status[:jafsent]  ) ,method: :put%></li>
    <li><%= link_to "JAF Filled" ,updatestatus_company_path(@company,status: Global.status[:jaffilled]  ) ,method: :put%></li>
    <li><%= link_to "PPT Scheduled" ,updatestatus_company_path(@company,status: Global.status[:pptset]  ) ,method: :put%></li>
    <li><%= link_to "PPT Done" ,updatestatus_company_path(@company,status: Global.status[:pptdone]  ) ,method: :put%></li>
    <li><%= link_to "Test Scheduled" ,updatestatus_company_path(@company,status: Global.status[:testset]  ) ,method: :put%></li>
    <li><%= link_to "Test Completed" ,updatestatus_company_path(@company,status: Global.status[:testdone]  ) ,method: :put%></li>
    <li><%= link_to "Rejected Invitation" ,updatestatus_company_path(@company,status: Global.status[:rejected]  ) ,method: :put%></li>
    <li><%= link_to "No Vacancy" ,updatestatus_company_path(@company,status: Global.status[:novacancy]  ) ,method: :put%></li>
    <li><%= link_to "Contact later" ,updatestatus_company_path(@company,status: Global.status[:contactlater]  ) ,method: :put%></li>
    <li><%= link_to "Blacklisted" ,updatestatus_company_path(@company,status: Global.status[:blacklisted]  ) ,method: :put%></li>
  </ul>
</div>

app/views/companies/_updatedescription.html.erb
<div class="company-description-text">
  <%= simple_format(@company.description) %>

<button class="btn btn-inverse" id="company-description-edit-button">
  Edit Description</button>
</div>
<div class="company-description-form">
<%= form_for @company , 
  :url => { :action => "update", :id => @company.id }   do |g| %>
  <%= g.text_area :description , class: "span12", rows: 3%>
  <%= g.hidden_field :id %>
  <%= g.submit "Update Description",class:"btn btn-primary pull-right" %>
  <%= link_to "Cancel", "#" ,class: "btn btn-inverse", id: "company-description-cancel" %>
<% end %> 
</div>

app/views/companies/_updateteam.html.erb
<%= form_for @company , :url => { :action => "update", :id => @company.id } do |f| %>
  <%= f.text_field :team_tokens, 
  "data-pre" => @company.teams.map(&:attributes).to_json %>
  <%= f.hidden_field :id %>
  <%= f.submit "Save teams",class:"btn btn-primary pull-right" %>
<% end %> 

app/views/companies/edit.html.erb
<% provide(:title,'Update the company profile') %>
<div class="row pagination-centered">
  <div class="span12">
    <%= render 'companies/form' , object: @company %>
  </div>
</div> <!-- /container -->

app/views/companies/index.html.erb
<% provide(:title,"Companies") %>
<h1>Companies 
    <%= begin
          if params[:team_id] 
            "handled by #{Team.find(params[:team_id]).name}"
          elsif params[:user_id]
            "handled by #{User.find(params[:user_id]).name}"
          else
            ""
          end
        rescue
          ""
        end
      %>
  <small><% if current_user.poweruser?%><%=link_to "Add a new Company",new_company_path, class: "btn btn-inverse pull-right"%><%end%></small></h1>

<p>
  Download:
  <%= link_to "CSV", companies_path(format: "csv") %> |
  <%= link_to "Excel", companies_path(format: "xlsx") %>
</p>
<hr />
<table class="table table-striped table-hover table-bordered" id="company-table">
  <thead>
    <tr>
      <th class="hidden-desktop hidden-tablet visible-phone">Details</th>
      <th class="hidden-phone">Name</th>
      <th class="hidden-phone hidden-tablet hidden-desktop">Location</th>
      <th class="hidden-phone">Status</th>
      <th class="hidden-phone">SPO Contact</th>
      <th class="hidden-phone">Last Contact</th>
      <th class="hidden-phone">HR Name</th>
      <th class="hidden-phone">HR Contact</th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
    <tr>
      <td class="hidden-desktop hidden-tablet visible-phone"><%=link_to company.name, company%> 
        <%= company.status_text %> 
      </td>
      <td class="hidden-phone"><%= link_to company.name, company%></td>
      <td class="hidden-phone hidden-tablet hidden-desktop"><%= company.location %></td>
      <td class="hidden-phone"><%= company.status_text  %></td>
      <td class="hidden-phone">
        <% begin %>
          <%= company.poc_name%>
        <% rescue %>
          <%= "No SPO Contact" %>
        <% end %>
      </td>
      <td class="hidden-phone">
        <% begin %>
          <% time=company.logs.order('created_at DESC').first.created_at %>
          <%= "#{time.strftime('%d %b %y')}
               <br/>#{time_ago_in_words(time)}".html_safe %>
        <% rescue %>
          <%= "Not contacted" %>
        <% end %>
      </td>
      <td class="hidden-phone">
        <% begin %>
          <%= company.default_contact.name %>
        <% rescue %>
          <%= "No default HR" %>
        <% end %>
      </td>
      <td class="hidden-phone">
        <% begin %>
          <% contact=company.default_contact %>
          <%= "<a href='tel: #{contact.mobile}'>#{contact.mobile}</a> (M)
          <br />
          <a href='tel:#{contact.landline}'>#{contact.landline}</a> (O)
          <br/>
          <a href='mailto:#{contact.email}'>#{contact.email}</a>".html_safe %>
        <% rescue %>
          <%= "No HR Contact" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/index.xls.erb
<table border="1">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
  </tr>
  <% @companies.each do |product| %>
  <tr>
    <td><%= product.id %></td>
    <td><%= product.name %></td>
    <td><%= product.address %></td>
    <td><%= product.phone %></td>
  </tr>
  <% end %>
</table>

app/views/companies/index.xlsx.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Address</Data></Cell>
        <Cell><Data ss:Type="String">Location</Data></Cell>
        <Cell><Data ss:Type="String">Phone</Data></Cell>
        <Cell><Data ss:Type="String">URL</Data></Cell>
        <Cell><Data ss:Type="String">Point of Contact</Data></Cell>
        <Cell><Data ss:Type="String">Manager</Data></Cell>
        <Cell><Data ss:Type="String">Team Tokens</Data></Cell>
        <Cell><Data ss:Type="String">Description</Data></Cell>
        <Cell><Data ss:Type="String">Status</Data></Cell>
        <Cell><Data ss:Type="String">Status Text</Data></Cell>
        <Cell><Data ss:Type="String">Last Contacted</Data></Cell>
        <Cell><Data ss:Type="String">HR Name</Data></Cell>
        <Cell><Data ss:Type="String">HR Contact</Data></Cell>

      </Row>
    <% @companies.each do |company| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= company.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= company.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= company.address %></Data></Cell>
        <Cell><Data ss:Type="String"><%= company.location %></Data></Cell>
        <Cell><Data ss:Type="String"><%= company.phone %></Data></Cell>
        <Cell><Data ss:Type="String"><%= company.url %></Data></Cell>
        <Cell><Data ss:Type="String"><%= company.poc_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= company.manager_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= company.team_tokens %></Data></Cell>
        <Cell><Data ss:Type="String"><%= company.description %></Data></Cell>
        <Cell><Data ss:Type="String"><%= company.status %></Data></Cell>
        <Cell><Data ss:Type="String"><%= company.status_text %></Data></Cell>
        <Cell><Data ss:Type="String"><% begin %>
          <% time=company.logs.order('created_at DESC').first.created_at %>
          <%= "#{time.strftime('%d %b %y')}
               <br/>#{time_ago_in_words(time)}"%>
        <% rescue %>
          <%= "Not contacted" %>
        <% end %></Data></Cell>
        <Cell><Data ss:Type="Number"> <% begin %>
          <%= company.default_contact.name %>
        <% rescue %>
          <%= "No default HR" %>
        <% end %></Data></Cell>
        <Cell><Data ss:Type="String"><% begin %>
          <% contact=company.default_contact %>
          <%= "tel: #{contact.mobile}#{contact.mobile} (M)
          <br />
          'tel:#{contact.landline}'#{contact.landline} (O)
          <br/>
          mail:#{contact.email}#{contact.email}" %>
        <% rescue %>
          <%= "No HR Contact" %>
        <% end %></Data></Cell>



      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/companies/new.html.erb
<% provide(:title,'Add a Company') %>
<div class="row pagination-centered">
  <div class="span12">
    <%= render 'companies/form' , object: @company %>
  </div>
</div> <!-- /container -->

app/views/companies/show.html.erb
<% provide(:title,@company.name) %>
<div class="container-fluid">
  <div class="row-fluid span12">
  <div class="span4" id="section1">
    <!-- Heeader with company details -->
    <div class="span12">
      <h1 class="heading">
        <%= @company.name %>
        <%= render 'companies/editbutton', object: @company, right: false %>
        <%= render 'companies/statuslist', object: @company %>
      </h1> 
      <div>
        <%= link_to "#{@company.url}" ,@company.url %>
      </div>
      <div>
          <p><%= @company.phone%></p>
          <p><%= @company.address %></p>
      </div> 
      <div>
          <p>Point of Contact :
            <%= if @company.pointofcontact  
                  link_to @company.pointofcontact.name, @company.pointofcontact 
                end
            %></p>
          <p>Managed by : 
            <%= if @company.manager 
                  link_to @company.manager.name, @company.manager 
                end
            %></p>
      </div>
      <hr /> 
    </div>

    <!-- Contact Details -->
    <div>
      <% unless @company.contacts.empty? %>
        <h4 class="heading">Contact</h4>
        <p>
          <% if @default && @default.active %>
            <strong><%= link_to @default.name, show_modal_company_contact_path(:company_id => @company.id,:id => @default.id), {:remote => true, 'data-controls-modal' =>  "contact-modal",'data-toggle'=>'modal', 'data-target'=>'#contact-modal'} %></strong>
            <%= "(#{@default.designation})" %> 
            <span class="badge badge-info pull-right">Default</span>
          <br><tel><%= "(M) #{@default.mobile}, (Off) #{@default.landline}" %>
          <br><a href='mailto:<%=@default.email%>'><%= @default.email %></a></p>
        <% else %>
        <%= "Set any of the contacts below as default" %>
        <% end %>
          <h5 class="heading">All contacts <small><%= link_to "Add Contact", new_company_contact_path(:company_id => @company.id),:class => "pull-right" %> </small></h5>
        <% # @i=0 %>
        <% @company.contacts.each do |contact| %>
           <% unless contact.deleted? %>
             <%= link_to contact.name, show_modal_company_contact_path(:company_id => @company.id,:id => contact.id), {:remote => true, 'data-controls-modal' =>  "contact-modal",'data-toggle'=>'modal', 'data-target'=>'#contact-modal'} %><br/>
           <% end %>
        <% end %>
      <% else %>
       <h1> </h1><h1></h1>
        <div class="pagination-centered">
          <%= link_to "Add Contact", new_company_contact_path(:company_id => @company.id),:class => "btn btn-inverse" %> 
        </div>
      <% end %>
      <br/>
    </div>
    
    <hr />
    <div>
        <h4>Teams with access </h4>
        <%= render 'companies/updateteam', object: @company%>
    </div>
  </div>
  <div class="span8">
    <div class="span12">
      <h4>About the company</h4>
        <%= render 'companies/updatedescription', object: @company%>
    </div>
    <hr />
    <div>
      <%= render 'companies/newlog' , object: { @company => @company, @newlog => @newlog, @contacts => @contacts } %>
    </div>
    <div>
      <% if @company.logs.any? %>
          <div class="logs">
            <%= render @logs %>
          </div>
        <%= will_paginate @logs %>
        <% end %>
    </div>   
      
  </div>
  </div>
</div>
<div class="modal hide fade" id="contact-modal">
  <div class="modal-header">
    <a a href="#" data-dismiss="modal" aria-hidden="true" class="close">×</a>
    <h3>Loading...</h3>
  </div>
  <div class="modal-body center">
      <%= image_tag "loading.gif" %>
  </div>
  <div class="modal-footer">&nbsp;</div>

</div>