config/routes.rb
Trackr::Application.routes.draw do
  

  resources :companies do
    put :activity, :on => :member
    put :updatestatus, :on => :member
    resources :contacts, :on => :member do
      get :show_modal, :on => :member
    end
    resources :logs, only: [:create, :destroy, :update, :edit]
    get :autocomplete_user_name, :on => :collection
  end
  resources :users do
    put :editlevel, :on => :member
    resources :companies, :on=> :member, only: [:index]
  end
  
  resources :teams do
    get :autocomplete_user_name, :on => :collection
    put :activity, :on => :member
    resources :companies, :on=> :member, only: [:index]
  end

  resources :contacts do
    put :activity, :on => :member
  end

  resources :logs, only: [:create, :destroy, :update, :edit]

  
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'static#home'

  match '/about',     to: 'static#about'
  match '/contactus', to: 'static#contact'
  match '/signup',    to: 'users#new'
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy', via: :delete

  match "/500", to:'static#500'
  match "/422", to:'static#422'
  match "/404", to:'static#404'
  

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_footer.html.erb
<hr />
<div class="container-fluid">
<nav class="navbar">
 
    Deployed by Students' Placement Office IIT Kanpur, Powered by Trackr from <a href="http://manyu.in">manyu.in</a>
 
  <div class="pull-right">
  <%= link_to "About",   about_path %> | 
  <%= link_to "Contact", contactus_path %>
  </div>
</nav>
</div>

app/views/layouts/_header.html.erb
<% provide(:user,'None') %>
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
            <div class="nav-collapse collapse">
            <nav>
                <a class="brand" href="/">Trackr</a>
                <ul class="nav pull-right">
                    <li><%= link_to "About",about_path %></li>
                    <% if signed_in? %>
                          <% if current_user.admin? %>
                          <li><%= link_to "Teams",teams_path %></li>
                          <li><%= link_to "Contacts",contacts_path %></li>
                          <% end %>
                          
                          <li><%= link_to "Companies",companies_path %></li>
                        

                           <li><%= link_to "Users",users_path %></li>
                                <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings",edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign Out",signout_path, method: "delete"   %>
                </li>
              </ul>
                </li>
                        <% else %>
                           <li> <%= link_to "Sign In",signin_path  %> </li>
                    <% end %>
                </ul>
            </nav>
          </div>
        </div>
    </div>
</header>
<hr/>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/htmljs"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <!--<%= javascript_include_tag "autocomplete-rails.js" %>-->
    <!--<%= stylesheet_link_tag "application", "token-input" %>  
    <%= javascript_include_tag :defaults, "jquery.tokeninput" %> -->
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
</head>
<body>
<div class="container-fluid">
<%= render 'layouts/header' %>
</div>
<div class="container-fluid">
<div class="row-fluid">
	<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
</div>

<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>